#version: "3.8"

services:
  backend:
    build: ./BackEnd
    ports:
      - "8000:8000"
    env_file:
      - .env

#  frontend:
#    depends_on:
#      - backend
#    image: react-frontend-ui-dev-v1.2.0
    #build:
    #  context: ./FrontEnd/user-ui/user-interface
    #  args:
    #    BACKEND_CONTAINER: backend
    #    BACKEND_PORT: 8000
#    ports:
#      - "3000:3000"
#    environment:
#      - BACKEND_CONTAINER=backend
#      - BACKEND_PORT=8000
