FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip

COPY requirements.txt /app

RUN pip install --no-cache -r requirements.txt

COPY . /app/

EXPOSE 7861

CMD ["python", "main.py"] 